version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.1.post1
    - 3.1.2
  - dependency-name: django-sendgrid-v5
    versions:
    - 0.9.0
  - dependency-name: billiard
    versions:
    - 3.6.3.0
  - dependency-name: pillow
    versions:
    - 6.2.0
